apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/k8s-monitoring
  contents:
  - path: .
    helmChart:
      name: k8s-monitoring
      version: 0.3.0
      repository:
        url: https://grafana.github.io/helm-charts
