apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: envs/zoo/_apps/metallb-system/vendor/ytt/
  contents:
  - path: config/manifests/
    git:
      url: https://github.com/metallb/metallb/
      ref: v0.13.12
    newRootPath: config/manifests/
    includePaths:
    - config/manifests/metallb-native.yaml
