---
# Sets the number of applications to be processed in parallel.
# The default (0) is no limit.
async: 1
# One of the zerolog log levels.
# See: https://github.com/rs/zerolog#leveled-logging
log-level: trace
# Load all binaries from the following folders as myks plugins.
plugin-sources:
    - ./plugins