apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/traefik
  contents:
  - path: .
    helmChart:
      name: traefik
      version: 10.14.1
      repository:
        url: https://helm.traefik.io/traefik
