#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ set_ns=data.values.myks.context.app
#@ if data.values.application.namespace.namespace:
#@   set_ns=data.values.application.namespace.namespace
#@ end

#! create namespace resource for each app
#@ if/end data.values.application.namespace.create:
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ set_ns


#! set namespace on all resources to match the app name
#! most helm charts are not setting the namespace for each document
#! warn: sometimes apps require multiple namespaces. This is currently not supported.
#@overlay/match by=overlay.all, expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: #@ set_ns
