#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
#@ environment = data.values.environment

---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden
type: Opaque
data:
  #! Username for authentication against the SMTP host.
  SMTP_USERNAME: #@ base64.encode("<path:secrets/{id}.vaultwarden.yaml#smtp_user>".format(id=environment.id))
  #! Password for authentication against the the SMTP host.
  SMTP_PASSWORD: #@ base64.encode("<path:secrets/{id}.vaultwarden.yaml#smtp_password>".format(id=environment.id))
  ADMIN_TOKEN: #@ base64.encode("<path:secrets/{id}.vaultwarden.yaml#admin_token>".format(id=environment.id))

