#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
#@ environment = data.values.environment


---
apiVersion: v1
kind: Secret
metadata:
  name: admin-user #! default for secretRefs.jwtSecretRef
type: Opaque
data:
  user-id: #@ base64.encode("<path:secrets/{id}.ocis.yaml#admin-id>".format(id=environment.id))
  password: #@ base64.encode("<path:secrets/{id}.ocis.yaml#admin-pass>".format(id=environment.id))
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret #! default for secretRefs.jwtSecretRef
type: Opaque
data:
  jwt-secret: #@ "<path:secrets/{id}.ocis.yaml#jwt-secret>".format(id=environment.id)

---
apiVersion: v1
kind: Secret
metadata:
  name: machine-auth-api-key #! default for secretRefs.machineAuthApiKeySecretRef
type: Opaque
data:
  machine-auth-api-key: #@ "<path:secrets/{id}.ocis.yaml#machine-auth-api-key>".format(id=environment.id)

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-system #! default for secretRefs.storagesystemSecretRef
type: Opaque
data:
  user-id: #@ "<path:secrets/{id}.ocis.yaml#user-id>".format(id=environment.id)
  api-key: #@ "<path:secrets/{id}.ocis.yaml#api-key>".format(id=environment.id)

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-system-jwt-secret #! default for secretRefs.storagesystemJwtSecretRef
type: Opaque
data:

  storage-system-jwt-secret: #@ "<path:secrets/{id}.ocis.yaml#storage-system-jwt-secret>".format(id=environment.id)

---
apiVersion: v1
kind: Secret
metadata:
  name: transfer-secret #! default for secretRefs.transferSecretSecretRef
type: Opaque
data:

  transfer-secret: #@ "<path:secrets/{id}.ocis.yaml#transfer-secret>".format(id=environment.id)

---
apiVersion: v1
kind: Secret
metadata:
  name: thumbnails-transfer-secret #! default for secretRefs.thumbnailsSecretRef
type: Opaque
data:
  thumbnails-transfer-secret: #@ "<path:secrets/{id}.ocis.yaml#thumbnails-transfer-secret>".format(id=environment.id)
---
apiVersion: v1
kind: Secret
metadata:
  name: notifications-smtp-secret #! needs to be set to `secretRefs.notificationsSmtpSecretRef`
type: Opaque
data:
  #! Username for authentication against the SMTP host.
  smtp-username: #@ base64.encode("<path:secrets/{id}.ocis.yaml#smtp_user>".format(id=environment.id))
  #! Password for authentication against the the SMTP host.
  smtp-password: #@ base64.encode("<path:secrets/{id}.ocis.yaml#smtp_password>".format(id=environment.id))

---
#! https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#configure-userlog-global-notifications-secret
#! Did not find any reference...
#! apiVersion: v1
#! kind: Secret
#! metadata:
#!   name: userlog-notifications-secret #! default of `secretRefs.globalNotificationsSecretRef`
#! type: Opaque
#! data:
#!   #! token
#!   notifications-secret: XXXXXXXXXXXXX
---
apiVersion: v1
data:
  ldap.crt: #@ "<path:secrets/{id}.ocis.yaml#ldap.crt>".format(id=environment.id)
  ldap.key: #@ "<path:secrets/{id}.ocis.yaml#ldap.key>".format(id=environment.id)
kind: Secret
metadata:
  name: ldap-cert
---
apiVersion: v1
data:
  ldap-ca.crt: #@ "<path:secrets/{id}.ocis.yaml#ldap-ca.crt>".format(id=environment.id)
kind: Secret
metadata:
  name: ldap-ca
---
apiVersion: v1
data:
  graph-ldap-bind-password: #@ "<path:secrets/{id}.ocis.yaml#graph-ldap-bind-password>".format(id=environment.id)
  idp-ldap-bind-password: #@ "<path:secrets/{id}.ocis.yaml#idp-ldap-bind-password>".format(id=environment.id)
  reva-ldap-bind-password: #@ "<path:secrets/{id}.ocis.yaml#reva-ldap-bind-password>".format(id=environment.id)
kind: Secret
metadata:
  name: ldap-bind-secrets

---
apiVersion: v1
data:
  encryption.key: #@ "<path:secrets/{id}.ocis.yaml#encryption.key>".format(id=environment.id)
  private-key.pem: #@ "<path:secrets/{id}.ocis.yaml#private-key.pem>".format(id=environment.id)
kind: Secret
metadata:
  name: idp-secrets
