deployment:
  initContainers:
  - name: volume-permissions
    image: busybox:1.31.1
    command:
    - sh
    - -c
    - chmod -Rv 600 /data/*.json
    volumeMounts:
    - name: data
      mountPath: /data
  - name: delay
    image: busybox:1.31.1
    command:
    - sh
    - -c
    - sleep 5s
pilot:
  enabled: false
  token: ""
  dashboard: false
ingressRoute:
  dashboard:
    enabled: true
    annotations: {}
    labels: {}
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true
metrics:
  prometheus:
    entryPoint: metrics
globalArguments:
- --global.checknewversion
additionalArguments:
- --certificatesresolvers.default.acme.storage=/data/acme-budd.ee.json
- --certificatesresolvers.default.acme.dnschallenge=true
- --certificatesresolvers.default.acme.dnschallenge.provider=httpreq
- --certificatesresolvers.default.acme.email=kris@budd.ee
- --entrypoints.web.http.redirections.entryPoint.scheme=https
- --entrypoints.web.http.redirections.entrypoint.permanent=true
- --entrypoints.web.http.redirections.entryPoint.to=:443
env:
- name: HTTPREQ_ENDPOINT
  value: http://mailinabox:8080
ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true
      options: ""
      certResolver: default
      domains: []
service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 192.168.178.220
    externalTrafficPolicy: Local
  loadBalancerSourceRanges: []
  externalIPs: []
persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  storageClass: longhorn
  path: /data
  annotations: {}
resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    memory: 150Mi
