#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
#@ environment = data.values.environment
---
apiVersion: v1
kind: Secret
metadata:
  name: mailinabox
data:
  MAILINABOX_PASSWORD: #@ base64.encode("<path:secrets/{id}.mailinabox.yaml#MAILINABOX_PASSWORD>".format(id=environment.id))
  MAILINABOX_URL: #@ base64.encode("<path:secrets/{id}.mailinabox.yaml#MAILINABOX_URL>".format(id=environment.id))
  MAILINABOX_USER: #@ base64.encode("<path:secrets/{id}.mailinabox.yaml#MAILINABOX_USER>".format(id=environment.id))
