#@ load("@ytt:data", "data")

#@ app = data.values.application
---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
#@ for chart in app.helmCharts:
- path: #@ "charts/" + chart.name
  contents:
    - path: .
      helmChart:
        name: #@ chart.name
        version: #@ chart.version
        repository:
          url: #@ chart.url
#@ end
#@ for git in app.gitRepos:
- path: #@ git.outputPath or "ytt/"
  contents:
    - path: #@ git.path
      git:
        url: #@ git.url
        ref: #@ git.version
      newRootPath: #@ git.newRootPath
      includePaths: #@ git.includePaths
#@ end