#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
#@ environment = data.values.environment
#@ db_user = "linkwarden"
#@ db_pass = "<path:secrets/{id}.linkwarden.yaml#POSTGRES_PASSWORD>".format(id=environment.id)
---
apiVersion: v1
kind: Secret
metadata:
  name: linkwarden
stringData:
  NEXTAUTH_SECRET: #@ "<path:secrets/{id}.linkwarden.yaml#NEXTAUTH_SECRET>".format(id=environment.id)
  POSTGRES_USER: linkwarden
  DATABASE_URL: #@ "postgresql://{user}:{db_pass}@linkwarden-db:5432/{user}".format(user=db_user, db_pass=db_pass)
  POSTGRES_PASSWORD: #@ db_pass
