#@ load("@ytt:data", "data")

#@ app = data.values.application
---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: #@ "charts/" + app.name
    contents:
      - path: .
        git:
          url: #@ app.url
          ref: #@ "v" + app.version
        newRootPath: #@ "charts/" + app.name
