image:
  tag: 1.29.2-alpine
ingress:
  enabled: true
  hostname: vault.budd.ee
  class: ""
  nginxIngressAnnotations: false
domain: https://vault.budd.ee
storage:
  enabled: true
  size: 2Gi
  class: default
  dataDir: /data
signupDomains: budd.ee
smtp:
  host: box.budd.ee
  port: 465
  from: vault@budd.ee
  fromName: vaultwarden
  authMechanism: Login
  security: force_tls
  existingSecret: vaultwarden
  username:
    existingSecretKey: SMTP_USERNAME
  password:
    existingSecretKey: SMTP_PASSWORD
adminToken:
  existingSecret: vaultwarden
  existingSecretKey: ADMIN_TOKEN
