#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#! Match all ArgoCD resources: Application, AppProject, Secret.
#@overlay/match by=overlay.all, expects="1+"
---
#@overlay/match missing_ok=True
#@overlay/match-child-defaults missing_ok=True
metadata:
  annotations:
    myks.dev/environment: #@ data.values.environment.id
    app.kubernetes.io/source: #@ data.values.myks.gitRepoUrl
