apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: goldpinger
spec:
  endpoints:
    - interval: 60s
      path: /metrics
      port: http
      scrapeTimeout: 60s
  selector:
    matchLabels:
      app: goldpinger
